# Generated by Django 5.2.2 on 2025-06-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareerpath', '0002_jobs_applied_saved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applied',
            old_name='jobs',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='saved',
            old_name='jobs',
            new_name='job',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='epoch_timestamp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='max_salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='min_salary',
            field=models.IntegerField(),
        ),
    ]
