# Generated by Django 5.2.2 on 2025-06-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareerpath', '0003_rename_jobs_applied_job_rename_jobs_saved_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='max_salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='min_salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salary_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
