# Generated by Django 5.2.2 on 2025-06-28 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycareerpath', '0004_alter_jobs_desc_alter_jobs_max_salary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='link',
            new_name='employer_logo',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='company',
            new_name='employer_name',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='type',
            new_name='employment_type',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='logo',
            new_name='job_apply_link',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='desc',
            new_name='job_description',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='location',
            new_name='job_location',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='max_salary',
            new_name='job_max_salary',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='min_salary',
            new_name='job_min_salary',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='epoch_timestamp',
            new_name='job_posted_at_timestamp',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='salary_type',
            new_name='job_salary_period',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='title',
            new_name='job_title',
        ),
    ]
