# Generated by Django 5.2.2 on 2025-06-28 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycareerpath', '0005_rename_link_jobs_employer_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='employer_name',
            new_name='job_employer_name',
        ),
    ]
