# Generated by Django 5.2.2 on 2025-06-28 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycareerpath', '0006_rename_employer_name_jobs_job_employer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='job_employer_name',
            new_name='employer_name',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='employment_type',
            new_name='job_employment_type',
        ),
    ]
