# Generated by Django 5.2.2 on 2025-06-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareerpath', '0007_rename_job_employer_name_jobs_employer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied',
            name='offer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='applied',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
