# Generated by Django 5.2.2 on 2025-07-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareerpath', '0008_applied_offer_applied_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='applied',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
