# Generated by Django 5.2.2 on 2025-07-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareerpath', '0009_applied_updated_alter_applied_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_posted_at_timestamp',
            field=models.IntegerField(null=True),
        ),
    ]
