# Generated by Django 5.2.2 on 2025-07-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareerpath', '0010_alter_jobs_job_posted_at_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
