# Generated by Django 5.2.2 on 2025-07-02 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareerpath', '0011_jobs_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('job_title', models.CharField(max_length=200)),
                ('employer_name', models.CharField(max_length=200)),
                ('job_location', models.CharField(max_length=100)),
                ('job_apply_link', models.URLField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('offer', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_job', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
